### ISSUE TITLE
CMakeLists.txt in multistep

### ISSUE THREAD

**Issue by hbsun2113** [HPCGraphAnalysis/Connectivity#4]
I use Clion,this project doesnt have CMakeLists.txt in multistep.Can you provide me with the CMakeLists.txt?

**Comment by gslota** [comment]
We just use a simple Makefile to build, so we therefore don't have any cmake files available, unfortunately. The build procedure is simple enough (just calling the compiler on scc_main) that you should be able to easily produce anything necessary for your environment.
